apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: payment 
spec:
  type: ClusterIP
  replicas: 3
  template:
    metadata:
      labels:
        app: payment 
    spec:
      containers:
        - name: payment 
          image: admin9.azurecr.io/payment
          ports:
          - containerPort: 8080
